title = "Programming Expiriments | Ajmal M A"
baseURL = "https://new-programmer.netlify.com/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Some notes on my programming expiriments"
  facebook = ""
  twitter = "https://twitter.com/ValidCoder"
  instagram = ""
  youtube = ""
  github = "https://github.com/ajmal1990"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/870450/ajmal-m-a"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
